version: '3.8'

services:
  web:
    build:
      context: ./$DJANGO_PROJECT_NAME
      dockerfile: Dockerfile.prod
    command: gunicorn $DJANGO_PROJECT_NAME.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/$DJANGO_PROJECT_NAME/web/staticfiles
      - media_volume:/home/$DJANGO_PROJECT_NAME/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/$DJANGO_PROJECT_NAME/web/staticfiles
      - media_volume:/home/$DJANGO_PROJECT_NAME/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  prod_postgres_data:
  static_volume:
  media_volume: